### ISSUE TITLE
Characters Not Displaying Correctly.

### ISSUE THREAD

**Issue by OwenMelbz** [FokkeZB/FontAwesomeJS#2]
Have got an Alloy project, trying to use FA,

My FontAwesome.otf is located here `/New App/app/assets/iphone/fonts/FontAwesome.otf`
fa.js is located here `/New App/app/lib/FontAwesome.js`

Alloy.js
`Alloy.Globals.Fa = require('/FontAwesome');`

widget.tss
~~~
".back_button" : {
	backgroundColor: Alloy.CFG.green,
	width: 100,
	height: 100,
	borderRadius: 50,
	
	top: 0,
	left: 0,
	zIndex: 999,
	
	font: {
		fontFamily: 'FontAwesome'
	},
	title: Alloy.Globals.Fa.android
}
~~~

and when I run the app using SDK 3.5.0 GA on iOS 8.1 iPhone 6 Simulator I get this

![Bug Screenshot](http://s23.postimg.org/3ys6fz6wb/bugbugbug.jpg)

Any ideas?

**Comment by OwenMelbz** [comment]
I've swapped out the .otf for the .ttf and the issue resolved itself - maybe its worth adding a foot note somewhere?

**Comment by FokkeZB** [comment]
The Appcelerator Documentations say that `.otf` should work as well, but I always use `.ttf` myself. I'll add a note.

**Comment by FokkeZB** [comment]
On second thought... I do use the `.otf` font in all of my apps and it has always worked without any problem. Maybe you needed to do a `ti clean` before it worked?

**Comment by OwenMelbz** [comment]
I had cleaned it several times, I even resorted to trying out different font packages, they all worked which was strange, but the moment I added in the .ttf version of FA it instantly worked without evening cleaning the build

**Comment by FokkeZB** [comment]
Well if other fonts did work with `.otf`, then it's a FontAwesome specific problem, that probably then didn't exist in earlier version of the font. I will close the issue adding a note.

**Comment by OwenMelbz** [comment]
Very peculiar, yes feel free to close thanks :)
